name = "vera-casa-os-v2"
main = "worker.js"
compatibility_date = "2026-10-01"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "vera-memory"
database_id = "ab102cb1-6fe8-4380-bbe5-e7b69f4a28c9"

[vars]
SHOPIFY_STORE = "v4rrxn-xe.myshopify.com"
SHOPIFY_CLIENT_ID = "a56dfaa473f3582692c1ab5d2a9cc502"

[assets]
directory = "./public"
binding = "ASSETS"
